const fs = require("node:fs/promises");
const { unchanged, readRow } = require("./files.cjs");
async function inspect(row) {
  await unchanged(row);
  let bytes;
  if (row.member) bytes = (await readRow(row)).subarray(0, 131072);
  else {
    const handle = await fs.open(row.path, "r");
    try {
      const buffer = Buffer.alloc(Math.min(row.size, 131072));
      const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0);
      bytes = buffer.subarray(0, bytesRead);
    } finally {
      await handle.close();
    }
  }
  const text = bytes.toString("utf8");
  const facts = [];
  if (["gcode", "gco", "g"].includes(row.ext)) {
    if (/(?:^|\n)\s*[GMT]\d+(?:\s|$)/m.test(text))
      facts.push(
        "Machine instruction commands detected. This does not confirm printer or machine compatibility.",
      );
    for (const line of text.split(/\r?\n/)) {
      if (
        /^\s*;.*(generated by|slicer|estimated printing time|filament used|layer_height|layer height|printer_model|print time|^;TIME:)/i.test(
          line,
        )
      )
        facts.push(line.replace(/^\s*;\s*/, "").slice(0, 220));
      if (facts.length >= 9) break;
    }
  } else if (row.ext === "blend" && text.startsWith("BLENDER"))
    facts.push(
      `Blender file signature found; stored version ${text.slice(9, 12)}.`,
    );
  else if (["step", "stp"].includes(row.ext) && text.includes("ISO-10303-21")) {
    facts.push("STEP exchange format signature confirmed.");
    const product = text.match(/PRODUCT\s*\(\s*'([^']*)'\s*,\s*'([^']*)'/i);
    if (product)
      facts.push("Embedded product name: " + (product[2] || product[1]));
  } else if (
    row.ext === "scad" &&
    /\b(module|cube|cylinder|sphere|difference|union)\s*\(/.test(text)
  )
    facts.push(
      "OpenSCAD modeling expressions found. Source is inspected as text and never executed.",
    );
  else if (row.ext === "obj" && bytes.includes(0))
    facts.push(
      "Contains binary data. This may be a compiled object file instead of a Wavefront model.",
    );
  return { facts, scope: "First 128 KiB inspected", empty: row.size === 0 };
}
module.exports = { inspect };
